### ISSUE TITLE
تغییر جای دیکشنری های FOODS و ADJS

### ISSUE THREAD

**Issue by AmiiirCom** [iamvee/karafs#15]
به نظرم بهتره که دیکشنری ها  تبدیل به یه فایل json بشه و در کنار برنامه قرار بگیره و خونده بشه

**Comment by parsampsh** [comment]
> به نظرم بهتره که دیکشنری ها تبدیل به یه فایل json بشه و در کنار برنامه قرار بگیره و خونده بشه

فایل جیسون که نه بهتره به ی اسکریپت دیگه مثلا به اسم `data.py` منتقل بشه. اینجوری توی برنامه هم در دسترسه.

**Comment by AmiiirCom** [comment]
> > به نظرم بهتره که دیکشنری ها تبدیل به یه فایل json بشه و در کنار برنامه قرار بگیره و خونده بشه
> 
> فایل جیسون که نه بهتره به ی اسکریپت دیگه مثلا به اسم `data.py` منتقل بشه. اینجوری توی برنامه هم در دسترسه.

فرقی نداره، فقط جدا بشه از برنامه اصلی اوکیه

**Comment by parsampsh** [comment]
من منتظرم پی آر #14 مرج بشه که برم سراغ این کار.
