### ISSUE TITLE
استفاده به عنوان کتابخانه

### ISSUE THREAD

**Issue by parsampsh** [iamvee/karafs#9]
در حال حاضر میشه این ابزار رو فقط توی خط فرمان استفاده کرد. @iamvee ایده ای برای اینکه مثلا بشه ایمپورتش کرد و اسم های رندوم رو تو برنامه استفاده کرد نداری؟

**Comment by iamvee** [comment]
اوکی من سعی می‌کنم تو این هفته این رو روالش کنم. البته یه داستان دیگه هم هست که باید بتونم بدون وایت اسپیس هم جنریت کنم. اینو هم باید اوکی کنم

**Comment by parsampsh** [comment]
> اوکی من سعی می‌کنم تو این هفته این رو روالش کنم. البته یه داستان دیگه هم هست که باید بتونم بدون وایت اسپیس هم جنریت کنم. اینو هم باید اوکی کنم

ی فلگ به اسم مثلا `--no-space` میتونه باشه. اگه میخوای من میتونم اوکیش کنم این فلگو.
